### ISSUE TITLE
time 不是中国时间

### ISSUE THREAD

**Issue by xmlgrg** [leoiceo/OpenSA#13]
你好，安装后，系统内有些时间不是中国时间呢
![image](https://user-images.githubusercontent.com/26371464/112857703-b430b900-90e3-11eb-93f6-570e4ea21f9e.png)

**Comment by leoiceo** [comment]
在Django的配置文件settings.py中USE_TZ = False, TIME_ZONE = ‘Asia/Shanghai'

**Comment by xmlgrg** [comment]
tks
